datadog:
  api_key: '[api key]'
  app_key: '[app key]'
default: true
jira:
  password: '[password]'
  server: https://example.jira.com
  username: '[username]'
local:
  log_file: /var/log/jiradog/jiradog.log
  metric_file: /etc/jiradog/metrics.json
